### ISSUE TITLE
Expose JobInfo parameters like requiresCharging, storageNotLow, etc

### ISSUE THREAD

**Issue by cbenhagen** [talkdirty/android_job_scheduler#4]

**Comment by talkdirty** [comment]
Yep, this is the next thing on the roadmap.

**Comment by cbenhagen** [comment]
Nice :)

**Comment by talkdirty** [comment]
`RequiresCharging`, `RequiresStorageNotLow`, `RequiredNetworkType` & also Reboot Persistence is implemented as of `0.0.6`, which should cover the most common use cases. Let me know if there are any issues.
